manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mollerdaniel
      url-base: https://github.com/mollerdaniel
  projects:
    - name: zmk-config
      remote: mollerdaniel
      revision: main
      import: app/west.yml
  self:
    path: config
